### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by ahmadawais** [stevegrunwell/wp-enforcer#15]
I added a few problems in my code to see if it works, but I am commiting code and nothing happens. 
I am using Mac, testing a plugin and I have installed it just the way you wrote and added extra config in the composer.json.

What could be wrong?

**Comment by stevegrunwell** [comment]
Hey @ahmadawais, thanks for the bug report. Let's see if we can triage this, shall we?

First, can you please verify the version of WP Enforcer you have installed? There have been a few releases in the last week, and I want to make sure it's not a problem that's already been solved.

If you run `./vendor/bin/phpcs` from the root of the repository, what output do you see? If the answer is "none", then the changes you made might not be egregious enough to trigger PHP_CodeSniffer. An easy way to check is inserting something like this:

``` php
if('foo' == 'bar'){
             echo "baz";
}
```

That block should set off all sorts of whitespace alarms :)

Next, please verify that your Git repository has a "pre-commit" hook (e.g. .git/hooks/pre-commit). The contents of the file should look [something like what's in the repository](https://github.com/stevegrunwell/wp-enforcer/blob/master/bin/hooks/pre-commit).

Finally, if PHP_CodeSniffer is finding a problem and the hook is in place but you're able to commit that bogus code, please try swapping out the contents of the pre-commit hook with [the version from the release/0.4.0 branch](https://github.com/stevegrunwell/wp-enforcer/blob/release/0.4.0/bin/hooks/pre-commit), which was adjusted in #13. If that solves it, I'll get a point release pushed out this morning to expedite that fix.

Thanks again for the report, and I'll look forward to hearing back from you!

**Comment by ahmadawais** [comment]
@stevegrunwell Now it seems to be working. I guess you fixed something. 

Is that how it works? Does it not provide any info on what and where is the problem?
![image](https://cloud.githubusercontent.com/assets/960133/11499835/db80fd5e-984a-11e5-8b42-c9180b403a33.png)

**Comment by stevegrunwell** [comment]
@ahmadawais what all does your `gcma` alias do? The output should look something like this:

``` bash
MacBook-Pro:wp-enforcer steve$ git add index.php
MacBook-Pro:wp-enforcer steve$ git commit -m "This file is riddled with errors"
Running PHP CodeSniffer...

FILE: /Users/steve/Sites/httpdocs/wp-enforcer/index.php
----------------------------------------------------------------------
FOUND 10 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 1 | ERROR | [ ] Missing file doc comment
 3 | ERROR | [ ] Empty IF statement detected
 3 | ERROR | [x] Expected 1 space after IF keyword; 0 found
 3 | ERROR | [x] Space after opening control structure is required
 3 | ERROR | [x] No space before opening parenthesis is prohibited
 3 | ERROR | [x] No space after opening parenthesis is prohibited
 3 | ERROR | [x] Expected 1 space after closing parenthesis; found 0
 3 | ERROR | [x] No space before closing parenthesis is prohibited
 3 | ERROR | [x] Space between opening control structure and closing
   |       |     parenthesis is required
 5 | ERROR | [x] File must end with a newline character
----------------------------------------------------------------------
PHPCBF CAN FIX THE 8 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 102ms; Memory: 4.75Mb

Please fix coding standards errors before committing
```

**Comment by stevegrunwell** [comment]
@ahmadawais let's revisit this when 0.4.0 drops – there have been a _lot_ of updates and hopefully we'll get closer to the expected behavior :smile: 

You can also update your composer.json to pull from the `release/0.4.0` branch in the meantime.

**Comment by ahmadawais** [comment]
@stevegrunwell gcma is git commit all. Check [here](https://github.com/ahmadawais/dotFiles/blob/master/.zshrc#L118-L123).

I thought it would run for all files, shouldn't it?

**Comment by stevegrunwell** [comment]
In the very first release (0.1.0), the entire codebase was being run through PHP_CodeSniffer, which meant integrating WP Enforcer on an existing codebase could be a _painful_ process. In #1 I adjusted this behavior so that only the files that are staged for commit are being checked; this way, if you're only touching functions.php in your commit you're not held liable for index.php, which you may or may not have _ever_ touched.

You're still able to run PHP_CodeSniffer against the entire codebase, but I'd recommend doing that in a cleanup branch (see "[Adding to an Existing Project](https://github.com/stevegrunwell/wp-enforcer#adding-to-an-existing-project)").

Does that clarify things for you?

**Comment by stevegrunwell** [comment]
@ahmadawais ping for ^ ?

**Comment by ahmadawais** [comment]
@stevegrunwell I'm going to try it next weekend, was busy with a WP Meetup.

**Comment by ahmadawais** [comment]
Forgot to mention, it's working fine :)

**Comment by stevegrunwell** [comment]
Fantastic, thanks for following up!
