### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by ericmann** [stevegrunwell/wp-enforcer#2]
Bash is awesome ... unless you're on a PC ... :-P

**Comment by stevegrunwell** [comment]
Would that be Powershell? Care to volunteer?

**Comment by ericmann** [comment]
Git can interact with any executable script on the OS. When I do cross-platform stuff, I typically have a `.sh` (or extensionless) Bash script for *NIX and a `.bat` script for Windows, both of which bootstrap and execute another, cross-platform, script (like Node, Python, or Ruby).

I'd be happy to take a crack at it, tho.

**Comment by stevegrunwell** [comment]
Awesome, thank you. Also, welcome to the project :)

**Comment by ericmann** [comment]
So I totally forgot that Git on Windows ships with a version of Cygwin. I've verified that Bash will work as a Git hook on Windows :-)
