### ISSUE TITLE
Require latest version of WPCS always

### ISSUE THREAD

**Issue by ghost** [stevegrunwell/wp-enforcer#37]
Currently `composer.json` has a hard dependency on WPCS, and is using `0.10.0`. Because they're not at a 1.0 and the current rule is `^` this change will not be automatic for minor updates (only one a major lands will that be true). As a result, we need to update to the new standard manually.

**Comment by ghost** [comment]
https://github.com/jhabdas/wp-enforcer/blob/develop/CHANGELOG.md#042---2017-01-04

> Don't lock wp-coding-standards/wpcs to a single version.
> Remove the explicit package version in composer.json, add GitHub URLs.

Where are those changes?

**Comment by ghost** [comment]
@stevegrunwell could you let me know what versioning tool and changelog generator you are using to manage this project since they're not installed as a dev dependency? I <ins>may</ins> need to fork and want to be able to merge back together.

**Comment by stevegrunwell** [comment]
> Where are those changes?

That particular change was in a5218973, where the version number was bumped but, as you pointed out, the version number is still getting locked-in.

> @stevegrunwell could you let me know what versioning tool and changelog generator you are using to manage this project since they're not installed as a dev dependency? I may need to fork and want to be able to merge back together.

The versioning of the plugin is manual: each feature branch includes a relevant change to the CHANGELOG.md file (under the "[Unreleased]" header). When a new release is being prepared, I branch `release/x.x.x` off of `develop`, bump version numbers + update documentation accordingly, then merge `release/x.x.x` via a non-fast-forward merge into `master`, tag the release, then merge master into `develop`.

This approach ensures people can easily see features/fixes in `develop` that haven't yet hit a stable release, should they choose to use the more "bleeding-edge" version.

**Comment by ghost** [comment]
Please see https://github.com/stevegrunwell/wp-enforcer/pull/38#issuecomment-304508829 for my suggestion on how to enable future upgrades. Note that before dependencies go to `1.0.0` the `^` works differently and will not take a minor, assuming it works like NPM. That's why #35 is important.

**Comment by dave-green-uk** [comment]
hi @stevegrunwell @jhabdas I'm literally in the process of introducing this into our workflow, and I need to be able use some of the custom sniff rules that were introduced in WPCS 0.11.0 and 0.12.0. 

How can I go about this independently, before the version bump is made in this repo? Is it just a case of specifying a more recent version in `composer.json`?

Any guidance appreciated. Fantastic tool!

**Comment by stevegrunwell** [comment]
Hey @davetgreen, I just tagged version 0.5.0, which follows @jhabdas' recommendation to use `*` for the WPCS version, ensuring you should get the latest :)

**Comment by dave-green-uk** [comment]
@stevegrunwell you sir are an absolute **legend**

Much obliged /tiphat
