### ISSUE TITLE
How about a github bot?

### ISSUE THREAD

**Issue by bhubbard** [stevegrunwell/wp-enforcer#45]
I would love to see a cloud function that can do the following:

* Verify the repo is using latest version of WP Enforcer, maybe auto update it. 
* Submit a automatic pull request of phpcbf changes. I would see it working similar to how [imgbot](https://imgbot.net/) works.

**Comment by stevegrunwell** [comment]
That's a really interesting concept! It might make sense to approach this as a larger PHP_CodeSniffer bot — if a `phpcs.xml(.dist)` file exists in the repo, scan the PRs and submit feedback?

I know I don't necessarily have the bandwidth to take something like that on right now, but I'd love to see someone run with it!
