### ISSUE TITLE
Allow using phpcbf to enable automatically fixing minor items

### ISSUE THREAD

**Issue by bswatson** [stevegrunwell/wp-enforcer#6]
[PHP Code Beautifier and Fixer](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically) can be used to automatically fix many common or minor issues and would be great as an additional option.

**Comment by stevegrunwell** [comment]
Ooh, good call! I'm not a fan of that becoming the default behavior, but considering it's swapping out an executable (that's already present, as it comes in with PHP_CodeSniffer) it wouldn't be difficult to add a `--phpcbf` (or similar) flag to the installer to copy use that program in the hook instead.

**Comment by ghost** [comment]
> I'm not a fan of that becoming the default behavior

Agreed. A tool should never automatically modify someone's code. It should provide feedback and instruction to help them modify it themselves, whether done using a tool or an editor.

Please consider closing this issue if there is no follow-up action to be done here.

**Comment by stevegrunwell** [comment]
I'm going to lean on keeping this out of WP Enforcer, but there's a section within the [adding to an existing project](https://github.com/stevegrunwell/wp-enforcer#adding-to-an-existing-project) section of the README that covers `phpcbf` usage.
