### ISSUE TITLE
Add option to use WordPress.com VIP coding standards

### ISSUE THREAD

**Issue by stevegrunwell** [stevegrunwell/wp-enforcer#7]
I mentioned it in a tweet to @Tarendai this evening, so I'd might as well add it here:

Considering PHP_CodeSniffer supports the VIP Coding Standards, it wouldn't take much effort to create a branch that uses those standards. Alternately, a `--vip` option during installation could make WP Enforcer helpful for VIP projects.

**Comment by bswatson** [comment]
+1 for --vip.

**Comment by stevegrunwell** [comment]
Agreed. Easiest way would be a phpcs.xml.sample-vip file, then toggle which one gets copied based on the presence of a `--vip` option. Plus, of course, updating the relevant docs: the installation instructions and adding a section for "Using WordPress.com VIP Coding Standards" below the "Configuration" heading of the README for people who need to change standards mid-stream.

Other implications of this ticket are a "Help" option, so I've opened #8, which blocks completion of this ticket.

**Comment by stevegrunwell** [comment]
@daveross looked at the branch you sent me via HipChat last night, everything looks good for a PR with one exception: let's keep it to just `--vip` (not `-v`); I just added `-v` as an alias for `--version` and in CLI land `-v` is also often used for `--verbose`.

Other than that, you took the exact approach I was going to (having a separate sample file in the repo to copy), so great minds something something :wink:. Please go ahead and get that PR submitted when you're able, it's one of the features I'm most looking forward to in 0.4.0!

**Comment by stevegrunwell** [comment]
Assigning this to myself; @daveross' PR will work well, I just need to write up docs + get the develop/master branches in order (#18).
